services:
  sql-server:
    container_name: sefimplus-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: [ "ACCEPT_EULA=Y", "SA_PASSWORD=${SQL_SERVER_PASSWORD}" ]
    ports: ["1433:1433"]
    networks: [app-network]
    volumes: [sql-data:/var/opt/mssql]

  app-redis:
    container_name: sefimplus-app-redis
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports: ["6379:6379"]
    networks: [app-network]
    volumes: [redis-data:/data]

  rabbitmq:
    container_name: sefimplus-rabbitmq
    image: rabbitmq:3-management-alpine
    ports: ["5672:5672","15672:15672"]
    environment: [ "RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}", "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}" ]
    networks: [app-network]
    volumes: [rabbitmq-data:/var/lib/rabbitmq]

  seq:
    container_name: sefimplus-app-seq
    image: datalust/seq:latest
    environment: [ "ACCEPT_EULA=Y", "SEQ_FIRSTRUN_ADMINUSERNAME=${SEQ_CONTAINER_ADMIN_USER}", "SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_CONTAINER_ADMIN_PASSWORD}" ]
    ports: ["5341:80"]
    networks: [app-network]
    volumes: [seq-data:/data]

  app-redis-insight:
    container_name: sefimplus-app-redis-insight
    image: redislabs/redisinsight:latest
    ports: ["5540:5540"]
    networks: [app-network]
    volumes: [redis-insight-data:/data]

networks: { app-network: { driver: bridge } }
volumes: { sql-data: {}, redis-data: {}, rabbitmq-data: {}, seq-data: {}, redis-insight-data: {} }
