services:
  app-api-dev:
    container_name: sefimplus-app-api-dev
    build: { context: ., dockerfile: App.Api/Dockerfile }
    image: local/appapi:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__SqlServer=Server=sql-server;Database=${SQL_SERVER_DB_DEV};User Id=${SQL_SERVER_USER};Password=${SQL_SERVER_PASSWORD};TrustServerCertificate=True;
    ports: ["5000:8080","5001:8081"]
    networks: [app-network]

  app-ui-dev:
    container_name: sefimplus-app-ui-dev
    build: { context: ., dockerfile: App.UI/Dockerfile }
    image: local/appui:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DOTNET_RUNNING_IN_CONTAINER=true
      - API_BASE_URL=http://app-api-dev:8080/
      - CacheSettings__ConnectionString=app-redis:6379,password=${REDIS_PASSWORD}
    ports: ["5002:8080","5003:8081"]
    networks: [app-network]
