services:


  app-api:
    container_name: app-api
    image: local/appapi
    build:
      context: .
      dockerfile: App.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__SqlServer=Server=sql-server;Database=SefimSuperAdmin;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True;
    ports:
      - "5190:8080"
      - "7190:8081"
    networks:
      - app-network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sql-server
      - seq


  app-ui:
    image: local/appui
    container_name: app-ui
    build:
      context: .
      dockerfile: App.UI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - DOTNET_RUNNING_IN_CONTAINER=true
      - API_BASE_URL=http://app-api:8080/
    ports:
      - "5191:8080"
      - "7191:8081"
    networks:
      - app-network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ui-keys:/app/key
    depends_on:
      - app-api
      - seq
      - app-redis 


  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: app-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - app-network


  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: app-rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq 
    networks:
      - app-network


  app-redis:
    image: redis:7-alpine
    container_name: app-redis
    command: redis-server --requirepass ProjectPassword
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: app-redis-insight
    ports:
      - "5540:5540"
    networks:
      - app-network
    depends_on:
      - app-redis
    volumes:
      - redis-insight-data:/data
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: app-seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=${SEQ_CONTAINER_ADMIN_USER}
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_CONTAINER_ADMIN_PASSWORD}
    volumes:
      - seq-data:/data
    networks:
      - app-network
  

  cloudflared:
    container_name: app-cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUD_TUNNEL_TOKEN}
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      app-ui:
        condition: service_started 



volumes:
  sql-data:
  rabbitmq-data:
  seq-data:
  ui-keys:
  redis-data:
  redis-insight-data:


networks:
  app-network:
    name: app-network 
    driver: bridge